Make minor coding-style change
Commit UUID: c9daad9f-cfc9-45cf-bbaf-a5976d56ef0c

diff --git a/trunk/git/git-branches b/trunk/git/git-branches
--- a/trunk/git/git-branches
+++ b/trunk/git/git-branches
@@ -33,13 +33,13 @@ do_sync_branch()
         cmd="git branch -f --no-track $1 $2"
     fi
 
-    eval echo "\"Running \\\"$cmd\\\"\"" 1>&2
+    eval echo "\"Running \\\"$cmd\\\"\"" >&2
 
     if [[ $force -ne 1 ]]; then
         confirm_cmd
         res=$?
         if [[ $res -ne 1 ]]; then
-            echo "Branch $b not reset" 1>&2
+            echo "Branch $b not reset" >&2
             test $res -eq 2 && return 1
             return 0
         fi
@@ -75,7 +75,7 @@ sync_with_bundles()
 }
 
 if ! declare -A branch_excl_set 2>/dev/null; then
-    echo "bash version 4.0 or greater is required" 1>&2
+    echo "bash version 4.0 or greater is required" >&2
     exit 1
 fi
 
diff --git a/trunk/git/git-make-bundle b/trunk/git/git-make-bundle
--- a/trunk/git/git-make-bundle
+++ b/trunk/git/git-make-bundle
@@ -6,7 +6,7 @@ parse_cmdline()
     test $(basename "$0") = "git-make-bundles" && all_branches=1
 
     if [[ -z $1 ]]; then
-        echo "Must specify commit ID" 1>&2
+        echo "Must specify commit ID" >&2
         return 1
     fi
     commit=$1
@@ -55,7 +55,7 @@ get_bundle_path()
 }
 
 if ! declare -A branch_excl_set 2>/dev/null; then
-    echo "bash version 4.0 or greater is required" 1>&2
+    echo "bash version 4.0 or greater is required" >&2
     exit 1
 fi
 
diff --git a/trunk/git/git-remotes b/trunk/git/git-remotes
--- a/trunk/git/git-remotes
+++ b/trunk/git/git-remotes
@@ -13,7 +13,7 @@ get_remotes()
 }
 
 if ! declare -A remote_set 2>/dev/null; then
-    echo "bash version 4.0 or greater is required" 1>&2
+    echo "bash version 4.0 or greater is required" >&2
     exit 1
 fi
 
diff --git a/trunk/git/git-set-version b/trunk/git/git-set-version
--- a/trunk/git/git-set-version
+++ b/trunk/git/git-set-version
@@ -3,7 +3,7 @@
 set -e
 
 if [ ! -d .git ] && [ ! -f .git ]; then
-    echo "Current directory is not root of a Git repository" 1>&2
+    echo "Current directory is not root of a Git repository" >&2
     exit 1
 fi
 
@@ -60,7 +60,7 @@ else
     version=$1
 fi
 if [ -z "$version" ]; then
-    echo "Nonempty version string required" 1>&2
+    echo "Nonempty version string required" >&2
     exit 1
 fi
 
@@ -74,4 +74,4 @@ if [ $tagonly -eq 0 ]; then
     git commit --amend --no-edit
 fi
 git tag "$@" "v$version"
-echo "Version $version" 1>&2
+echo "Version $version" >&2
diff --git a/trunk/git/git-submodule-commit b/trunk/git/git-submodule-commit
--- a/trunk/git/git-submodule-commit
+++ b/trunk/git/git-submodule-commit
@@ -34,7 +34,7 @@ get_commit_message()
 }
 
 if ! declare -A excluded_submodules 2>/dev/null; then
-    echo "bash version 4.0 or greater is required" 1>&2
+    echo "bash version 4.0 or greater is required" >&2
     exit 1
 fi
 declare -a submodules
