Fix script to write error output to stderr
Commit UUID: 3ea57e41-94fc-4588-8f73-5068bd36939f

diff --git a/trunk/git/git-set-version b/trunk/git/git-set-version
--- a/trunk/git/git-set-version
+++ b/trunk/git/git-set-version
@@ -62,7 +62,7 @@ else
     version=$1
 fi
 if [ -z "$version" ]; then
-    echo "Nonempty version string required"
+    echo "Nonempty version string required" 1>&2
     exit 1
 fi
 
