Fix helper scripts to check for bash 4.0 as needed
Commit UUID: 06189f03-270c-4003-962c-ed5b8096c104

diff --git a/trunk/git/git-branches b/trunk/git/git-branches
--- a/trunk/git/git-branches
+++ b/trunk/git/git-branches
@@ -44,6 +44,11 @@ sync_with_bundles()
     do_sync "bundle_\$b/\$b"
 }
 
+if ! declare -A branch_excl_set 2>/dev/null; then
+    echo "bash version 4.0 or greater is required" 1>&2
+    exit 1
+fi
+
 set -e
 
 get_branches
@@ -60,8 +65,6 @@ if [[ $cmd = "sync" ]]; then
 fi
 
 if [[ $sync_origin = 0 ]] || [[ $sync_bundles = 1 ]]; then
-    declare -A branch_excl_set
-
     branches_excl=$(git config user.branchesExcl)
     for b in $branches_excl; do
         branch_excl_set[$b]=1
diff --git a/trunk/git/git-make-bundle b/trunk/git/git-make-bundle
--- a/trunk/git/git-make-bundle
+++ b/trunk/git/git-make-bundle
@@ -60,6 +60,11 @@ get_bundle_path()
     fi
 }
 
+if ! declare -A branch_excl_set 2>/dev/null; then
+    echo "bash version 4.0 or greater is required" 1>&2
+    exit 1
+fi
+
 multclones=$(git config user.multClones)
 
 set -e
@@ -71,8 +76,6 @@ get_branches
 get_bundle_path
 
 set +e
-
-declare -A branch_excl_set
 
 branches_excl=$(git config user.branchesExcl)
 for b in $branches_excl; do
diff --git a/trunk/git/git-remotes b/trunk/git/git-remotes
--- a/trunk/git/git-remotes
+++ b/trunk/git/git-remotes
@@ -15,9 +15,13 @@ get_remotes()
     done < <(echo "$tmp")
 }
 
+if ! declare -A remote_set 2>/dev/null; then
+    echo "bash version 4.0 or greater is required" 1>&2
+    exit 1
+fi
+
 set -e
 
-declare -A remote_set
 get_remotes
 
 set +e
diff --git a/trunk/git/git-submodule-commit b/trunk/git/git-submodule-commit
--- a/trunk/git/git-submodule-commit
+++ b/trunk/git/git-submodule-commit
@@ -28,9 +28,12 @@ get_commit_message()
     done
 }
 
-set -e
+if ! declare -A excluded_submodules 2>/dev/null; then
+    echo "bash version 4.0 or greater is required" 1>&2
+    exit 1
+fi
 
-declare -A excluded_submodules
+set -e
 
 get_excluded_submodules
 
